### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by andrewcurtis** [alpacaaa/zero-bullshit-haskell#18]
Hi, Great initiative here!

Newer stack builds report a deprecation warning :

 `DEPRECATED: The package at Archive from https://github.com/alpacaaa/zero-bullshit-haskell/archive/master.tar.gz in subdir library does not include a cabal file.
Instead, it includes an hpack package.yaml file for generating a cabal file.
This usage is deprecated; please see https://github.com/commercialhaskell/stack/issues/5210.
Support for this workflow will be removed in the future.`

Details:
stack 2.5.1.1 x86_64 hpack-0.34.3

**Comment by alpacaaa** [comment]
Thanks for letting me know! I'll look into it :)

**Comment by alpacaaa** [comment]
Fixed by https://github.com/alpacaaa/zero-bullshit-haskell/commit/9670aede1fad995fc801ef4ce99794088984967f.
