### ISSUE TITLE
Server.decodeJson is throwing an error 

### ISSUE THREAD

**Issue by KannepallyKoushik** [alpacaaa/zero-bullshit-haskell#20]
error:
    * No instance for (Aeson.FromJSON Person)
        arising from a use of `Server.decodeJson'
    * In the expression: Server.decodeJson body
      In the expression:
        case Server.decodeJson body of
          Left err
            -> "Failed to decode request body as a Person. It must be something else"
          Right p -> "Yay! We have a person named: " <> (name p)
      In an equation for `result':
          result
            = case Server.decodeJson body of
                Left err
                  -> "Failed to decode request body as a Person. It must be something else"
                Right p -> "Yay! We have a person named: " <> (name p)
   |
23 |       case Server.decodeJson body of

**Comment by alpacaaa** [comment]
where is this coming from? Could you paste your source file?

**Comment by KannepallyKoushik** [comment]
module Lib where

import qualified Data.Aeson as Aeson
import Data.Text
import GHC.Generics (Generic)
import qualified Zero.Server as Server

data Person = Person {name :: String, age :: Int}
  deriving (Generic, Aeson.FromJSON, Aeson.ToJSON)

myHandler :: Server.Request -> Server.Response
myHandler req =
  Server.stringResponse result
  where
    body =
      Server.requestBody req
    result =
      case Server.decodeJson body of
        Left err -> "Failed to decode request body as a Person. It must be something else"
        Right p -> "Yay! We have a person named: " <> (name p)

run :: IO ()
run =
  Server.startServer
    [ Server.simpleHandler Server.POST "/person" myHandler
    ]

**Comment by KannepallyKoushik** [comment]
And It throws another error that it cant Derive Aeson.FromJSON and Aeson.ToJSON

I'm currently building a budgedy project using Zero Bullshit Hackage
And I'm facing issue with these two errors

Can you please help me out sir!

**Comment by alpacaaa** [comment]
Did you set the `default-extensions` field in `package.yml`?

```yaml
default-extensions:
- OverloadedStrings
- DeriveGeneric
- DeriveAnyClass
```

**Comment by KannepallyKoushik** [comment]
I've set it now.
New to Haskell, Learning a lot from your repo.
Thankyou sir!

**Comment by alpacaaa** [comment]
You're welcome :)
