### ISSUE TITLE
I think I spotted an error

### ISSUE THREAD

**Issue by SpLauT** [alpacaaa/zero-bullshit-haskell#21]
Hello! I really think what you are doing here is grand!
I am in the mutable state area

counterHandler :: Int -> Server.Request -> (Int, Server.Response)
counterHandler currentCount
  = (newCount, response)
  where
    newCount
      = currentCount + 1
    response
      = Server.simpleHandler ("Current count: " ++ show newCount)

Where the counterHandler is, I think you wanted to use Server.stringResponse?
Also you only have the currentCount, and not the req as a parameter 

Only want to help, so if I am stupid just tell me to shut up! :)

**Comment by SpLauT** [comment]
main :: IO ()
main
  = Server.startServer
      [ Server.handlersWithState initialState [counterHandler]
      ]

I made this work with: Server.handlersWithState initialState [Server.statefulHandler Server.GET "/count" counterHandler]

**Comment by alpacaaa** [comment]
You're absolutely right, thanks for spotting this! :)
